[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction --no-scripts"]

[phases.build]
cmds = [
    "php artisan key:generate --show > /dev/null || true",
    "composer dump-autoload --optimize"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan config:clear && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"
