[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction --no-scripts"]

[phases.build]
cmds = ["composer dump-autoload --optimize"]
