[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "cp .env.example .env",
    "php artisan key:generate"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"
